version: '3.8'

services:
  app:
    build: .
    container_name: financial_ai_app
    restart: always
    env_file: .env
    ports:
      - "5000:5000"
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: "financial_ai_nginx"
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - app_network

networks:
  app_network:


